### ISSUE TITLE
Building on Mac

### ISSUE THREAD

**Issue by dkhan11** [swilly22/redis-module-graph#11]
Hi, 

I'm trying to build this on latest version of Mac OS and latest Redis(updated with brew).
cmake . && make all results:
[ 15%] Built target Llibgraph
[ 18%] Built target module
[ 34%] Built target test_agg_sum
[ 50%] Built target test_edge
[ 67%] Built target test_graph
[ 83%] Built target test_node
[100%] Built target test_triplet

And the module gets compiled.
But: redis-server --loadmodule src/libmodule.so 

Results in:
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'loadmodule "src/libmodule.so"'
Bad directive or wrong number of arguments

Any help will do. I would love to test your software!
Thanks,
DD.

**Comment by swilly22** [comment]
Hi,
Minimum required Redis version which supports modules is 4,
Download https://redis.io/download (4.0-rc2).

**Comment by dkhan11** [comment]
Thanks for the quick answer. 
My mistake! I built the latest version and it works:)
Thanks again,
DD.
