### ISSUE TITLE
Query structure

### ISSUE THREAD

**Issue by dkhan11** [swilly22/redis-module-graph#12]
Hi,

I'm trying to return a complete object and I'm not sure if it supported.
This works well, as documented:
GRAPH.QUERY presidents "MATCH (president)-[born]->(state:Hawaii) RETURN president.name, president.age"

While trying to return a complete 'president' object just hangs:
GRAPH.QUERY presidents "MATCH (president)-[born]->(state:Hawaii) RETURN president"

I'm also unable to catch any query errors. It just hangs. 
Any help will do.

BTW - the Demo works but it ALWAYS fires a one time error regarding the module:
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 5
>>> 'loadmodule "/Users/user/apps/temp/dast1/redis-module-graph-master/src/libmodule.so"'

    ** The file is located at the right place. The module was loaded successfully with redis-server.
    ** The samples work even if the file is not located at all. 

Thanks,
DD.

**Comment by swilly22** [comment]
Hi, returning a 'complete' object (without specifying it's properties) is currently not supported, I'll try to add support soon, 
Regarding the error you're experiencing I'll have to double check.

**Comment by dkhan11** [comment]
Got it. As a feature, I think that it is much needed.
If you have a good way to catch exceptions, please let me know. Otherwise, it is very hard to catch query errors. 
Thanks for the help,
DD.
