### ISSUE TITLE
Module failed to load

### ISSUE THREAD

**Issue by bazuka** [swilly22/redis-module-graph#18]
Hello Roi!
I've built your module using  comand 
`make module`
and when I'm trying to load it to redis im getting an error:

```root@ced26aa3098b:/redis-graph# redis-server --loadmodule $PWD/module/src/libmodule.so
168:C 24 Mar 11:14:19.657 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
168:C 24 Mar 11:14:19.657 # Redis version=999.999.999, bits=64, commit=00000000, modified=0, pid=168, just started
168:C 24 Mar 11:14:19.657 # Configuration loaded
... skipped awesome Redis logo...
168:M 24 Mar 11:14:19.659 # Server initialized
168:M 24 Mar 11:14:19.659 # Module /redis-graph/module/src/libmodule.so failed to load: /redis-graph/module/src/libmodule.so: undefined symbol: uuid_compare
168:M 24 Mar 11:14:19.659 # Can't load module from /redis-graph/module/src/libmodule.so: server aborting
```

OS is Debian 8 (jessie) x64 with uuid-dev installed.
Is there any extra dependencies i should resolve to make it run?

BTW, thank you for an awesome lib

**Comment by swilly22** [comment]
Hi bazuka,
My intention is to get rid of uuid, I'm going to replace this with rand really soon.
Thank you.

**Comment by esokullu** [comment]
@bazuka If you're on ubuntu you can install it with: sudo apt-get install uuid-dev

**Comment by bazuka** [comment]
@swilly22 Thank you, it would be great

@esokullu anyway, thank you for trying to help

**Comment by swilly22** [comment]
@bazuka I've just pushed a commit which removes the dependency on uuid,
Please give it a try.

**Comment by esokullu** [comment]
@swilly22 it works for me. Thanks. Can rand() be a long-term solution for this or are you planning to go back to uuid at some point?

**Comment by swilly22** [comment]
@esokullu Well although rand does not guarantee uniqueness, I'm not expecting query graphs (a graph describing search pattern) to contain such a high number of nodes for a collision to occur.

If there's a simple (hopefully dependency free) solution for generating unique ints, I'll be happy to consider.
Thanks

**Comment by bazuka** [comment]
@swilly22 Thank you, it works now. Will try to experiment with data now.

There was a blog post by @antirez about Generating unique IDs, hope it may help http://antirez.com/news/99
ps: so i'll close this issue since module loading is working for me now.
