### ISSUE TITLE
Windows binary to get casuals onboard?

### ISSUE THREAD

**Issue by m1sta** [swilly22/redis-module-graph#19]
Publishing a windows binary would go a long way towards getting more people trying redis-module-graph.  Maybe not the people you *want* though. There is a large audience for what you've built here that don't have any other need to work with C and so the whole make process feels scary, even though the actual product is exciting.

**Comment by itamarhaber** [comment]
A Windows binary (dll?) would first require a version of Redis on Windows that supports modules... Given that the MS Open Tech fork isn't maintained, I don't see it happening.

**Comment by esokullu** [comment]
@m1sta On Windows, you may feel more comfortable working with graphengine.io
