### ISSUE TITLE
Build fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by ryanlath** [swilly22/redis-module-graph#20]
Having trouble building this.  Error below: 

`ryan@NAS:~/tmp/redis-module-graph-master$ make
[ 15%] Built target Llibgraph
[ 18%] Built target module
[ 19%] Linking C executable test_agg_sum
CMakeFiles/test_agg_sum.dir/__/src/util/triemap/triemap.c.o: In function `TrieMap_RandomKey':
triemap.c:(.text+0x20f9): undefined reference to `log2'
triemap.c:(.text+0x20fe): undefined reference to `round'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_agg_sum.dir/build.make:770: recipe for target 'test/test_agg_sum' failed
make[2]: *** [test/test_agg_sum] Error 1
CMakeFiles/Makefile2:1083: recipe for target 'test/CMakeFiles/test_agg_sum.dir/all' failed
make[1]: *** [test/CMakeFiles/test_agg_sum.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
`
Thanks,
Ryan

**Comment by swilly22** [comment]
@ryanlath I've just added a Dockerfile which runs RedisGraph on Ubuntu, I know this is not the fix you were looking for but if you just wanted to test this module on Ubuntu and you don't mind using Docker you can pull and run from repository root folder:

docker build . -t redisgraph
docker run -p6379:6379 -d redisgraph

**Comment by swilly22** [comment]
README been update, instead of build all use build module.

**Comment by ryanlath** [comment]
make module works!  Thanks!
